services:
  - type: pserv
    repo: https://github.com/livekit-examples/agent-deployment
    rootDir: agent   # path to folder containing Dockerfile
    name: voice-agent
    runtime: docker  # <-- change this
    plan: starter
    envVars:
      - fromGroup: agent-example-env
    region: virginia
    maxShutdownDelaySeconds: 300
    scaling:
      minInstances: 1
      maxInstances: 4
      targetCPUPercent: 60
      targetMemoryPercent: 60
version: "1"
